# we use array here, becasue we may want to input more parameters later
hosts = {
  'controller' => [11],
  'compute1'   => [31]
}

Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-16.04'
  # Default is 2200..something, but port 2200 is used by forescout NAC agent.
  config.vm.usable_port_range = 3800..3900

  # Do not generate a key
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']
  config.vm.provision 'file', source: '~/.ssh/id_rsa.pub', destination: '~/.ssh/authorized_keys'

  hosts.each do |hostname, (hostip)|
    config.vm.define hostname.to_s do |box|
      box.vm.hostname = hostname.to_s
      box.vm.network :private_network, ip: "10.0.0.#{hostip}",   netmask: '255.255.255.0'
      box.vm.provider 'virtualbox' do |vb|
        vb.gui = false
        vb.memory = '8192'
        vb.cpus = 2
      end
      box.vm.provision :shell, path: "#{hostname}.sh"
    end
  end
end
