Vagrant.configure('2') do |config|
  config.vm.box = 'bento/ubuntu-16.04'

  # Do not generate a key
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']
  config.vm.provision 'file', source: '~/.ssh/id_rsa.pub', destination: '~/.ssh/authorized_keys'
  config.vm.network :private_network, ip: '10.33.3.33', netmask: '255.255.255.0'

  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = '10240'
  end
  config.vm.provision :shell, path: 'apt.sh'
end
