# we use array here, becasue we may want to input more parameters later
hosts = {
  '01-controller' => [200],
  '02-network' => [201]
}

Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/trusty64'
  # Default is 2200..something, but port 2200 is used by forescout NAC agent.
  config.vm.usable_port_range = 2800..2900

  # Cachier will cache the apt install between hosts
  unless Vagrant::Util::Platform.windows?
    if Vagrant.has_plugin?('vagrant-cachier')
      config.cache.scope = :box
      config.cache.enable :apt
      config.cache.synced_folder_opts = {
        type: :nfs,
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
    else
      puts '[-] WARN: This would be much faster if you ran vagrant plugin install vagrant-cachier first'
    end
  end

  hosts.each do |hostname, (hostip)|
    config.vm.define hostname.to_s do |box|
      box.vm.hostname = hostname.to_s
      box.vm.network :private_network, ip: "172.16.0.#{hostip}",    netmask: '255.255.0.0'
      box.vm.network :private_network, ip: "10.10.0.#{hostip}",     netmask: '255.255.255.0'
      box.vm.network :private_network, ip: "192.168.100.#{hostip}", netmask: '255.255.255.0'
    end
  end
end
