Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  # Do not generate a key
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.ssh/id_rsa', '~/.vagrant.d/insecure_private_key']
  config.vm.provision 'file', source: '~/.ssh/id_rsa.pub', destination: '~/.ssh/authorized_keys'
  config.vm.network :private_network, ip: "10.33.2.155",   netmask: '255.255.255.0'


  config.vm.provider 'virtualbox' do |vb|
    vb.cpus = 2
    vb.memory = '8192'
  end
  config.vm.provision :shell, path: 'apt.sh'

  # Cachier will cache the apt install between hosts
  unless Vagrant::Util::Platform.windows?
    if Vagrant.has_plugin?('vagrant-cachier')
      config.cache.scope = :box
      config.cache.enable :apt
      config.cache.synced_folder_opts = {
        type: :nfs,
        mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
      }
    else
      puts '[-] WARN: This would be much faster if you ran vagrant plugin install vagrant-cachier first'
    end
  end
end
